name: AnsibleTest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  check_ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: nginx.yaml
          syntax_check: true
